### ISSUE TITLE
🔥Add Domain Excluding Feature in Options Page

### ISSUE THREAD

**Issue by rbrahul** [rbrahul/Awesome-JSON-Viewer#25]
Add an input field to add domain listing to be excluded. Since some users are noticing for some websites they can't access the usual behavior like login etc.
The plugin will respect excludable domain listing before rendering.

**Comment by carsonl** [comment]
This comment is mostly a +1, however webex.com is one of the sites this 'barfs' on... it presents a beautifully presented json document... instead of allowing the browser to actually load the page and allowing me to join a call. I totally understand that the site is doing something wrong here, but it'd be nice to be able to just add a site to the blocklist in the extension, rather than disable the extension and reload the page...

**Comment by rbrahul** [comment]
This feature has been released in Version 1.1.2. Please give a try.
