### ISSUE TITLE
Performance with large data structures

### ISSUE THREAD

**Issue by julienvincent** [rbrahul/Awesome-JSON-Viewer#3]
Works great for small data-structures, however when it starts having to process large JSON trees (1000+) it freezes up. Might be something you want to look into :)

Either way, great work - very cool tool!

**Comment by rbrahul** [comment]
@julienvincent Thanks for your such observations. Can you please specify which portion it freezes? I think Chart view may have a problem because For 1000+ tree it has to create 1000+ nodes for your data. And each node may have tons of child node or branch. So generating such large image object is really resource consuming and obviously have some performance issue. Regarding this Issue, I have only option to limit the number of branches or nodes. I think It won't be possible. Then most of the user will be confused while visualizing their valuable data in a tree representation. Anyway, I am still trying to gain its performance for large data set. Thanks once again. :)

**Comment by julienvincent** [comment]
@rbrahul The chart view it completely freezes (I'm not sure if it does eventually render as I closed it after a minute or so).

The collapsable data view does render eventually, but is very slow and toggling the collapse state of nodes takes a long time to respond.

I understand the chart view might be very hard to improve performance, but there could be some options for the data view. Some ideas:

+ Default nested nodes to closed when data tree is large
+ Stop rendering nodes that are off-screen
+ Ensure best possible performance by using React's `shouldComponentUpdate` life-cycle hook (if you are not already doing this)
